<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>software.xdev</groupId>
		<artifactId>src</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	
	<artifactId>template-placeholder</artifactId>
	<packaging>jar</packaging>

	<name>template-placeholder</name>
	<description>template-placeholder</description>

	<properties>
		<generatedDirRelative>src/generated/java</generatedDirRelative>
		<generatedDir>${project.basedir}/${generatedDirRelative}</generatedDir>
	</properties>

	<dependencies>
		<!-- HTTP client: apache client -->
		<dependency>
			<groupId>org.apache.httpcomponents.client5</groupId>
			<artifactId>httpclient5</artifactId>
			<version>5.6.4</version>
		</dependency>

		<!-- JSON processing: jackson -->
		<dependency>
			<groupId>tools.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>3.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>0.2.11</version>
		</dependency>

		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<version>3.0.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.6.2</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${generatedDirRelative}</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>openapi-generator</id>
			<properties>
				<componentName>INSERT_NAME_HERE</componentName>

				<openApiRelativeGeneratorDir>src/gen</openApiRelativeGeneratorDir>
				<openApiGeneratorDir>
					${project.basedir}/target/generated-sources/openapi/${openApiRelativeGeneratorDir}
				</openApiGeneratorDir>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-clean-plugin</artifactId>
						<version>3.5.0</version>
						<executions>
							<execution>
								<id>pre-generation-clean</id>
								<phase>initialize</phase>
								<goals>
									<goal>clean</goal>
								</goals>
								<configuration>
									<excludeDefaultDirectories>true</excludeDefaultDirectories>
									<filesets>
										<fileset>
											<directory>${generatedDir}</directory>
										</fileset>
									</filesets>
								</configuration>
							</execution>
							<execution>
								<id>post-generation-clean</id>
								<phase>process-resources</phase>
								<goals>
									<goal>clean</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.openapitools</groupId>
						<artifactId>openapi-generator-maven-plugin</artifactId>
						<version>7.24.0</version>
						<executions>
							<execution>
								<goals>
									<goal>generate</goal>
								</goals>
								<configuration>
									<inputSpec>${project.basedir}/openapi/openapi.yml</inputSpec>
									<generatorName>java</generatorName>
									<configOptions>
										<sourceFolder>${openApiRelativeGeneratorDir}</sourceFolder>
										<library>apache-httpclient</library>
										<apiPackage>software.xdev.${componentName}.api</apiPackage>
										<modelPackage>software.xdev.${componentName}.model</modelPackage>
										<invokerPackage>software.xdev.${componentName}.client</invokerPackage>
										<!-- Otherwise throw and catch everywhere -->
										<useRuntimeException>true</useRuntimeException>
										<!-- Some fields of API have been ignored because they are unused -->
										<disallowAdditionalPropertiesIfNotPresent>false
										</disallowAdditionalPropertiesIfNotPresent>
										<!-- Use newer Jakarta EE instead of Javax -->
										<useJakartaEe>true</useJakartaEe>
										<hideGenerationTimestamp>true</hideGenerationTimestamp>
										<useJackson3>true</useJackson3>
									</configOptions>
									<!-- No tests and documentation because we don't use that -->
									<generateModelTests>false</generateModelTests>
									<generateApiTests>false</generateApiTests>
									<generateModelDocumentation>false</generateModelDocumentation>
									<generateApiDocumentation>false</generateApiDocumentation>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.5.0</version>
						<executions>
							<execution>
								<id>copy-generated-resources</id>
								<phase>process-sources</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${generatedDir}</outputDirectory>
									<resources>
										<resource>
											<directory>${openApiGeneratorDir}</directory>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>software.xdev</groupId>
						<artifactId>find-and-replace-maven-plugin</artifactId>
						<version>1.0.5</version>
						<executions>
							<execution>
								<!-- Remove so that we don't need additional dependency -->
								<id>remove-unused-import-com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider</id>
								<phase>process-sources</phase>
								<goals>
									<goal>file-contents</goal>
								</goals>
								<configuration>
									<baseDir>${generatedDirRelative}/software/xdev/${componentName}/client/</baseDir>
									<fileMask>ApiClient.java</fileMask>
									<!-- @formatter:off DO NOT INTRODUCE LINE BREAK -->
									<findRegex>^import com\.fasterxml\.jackson\.jaxrs\.json\.JacksonJsonProvider;(\r?\n)</findRegex>
									<!-- @formatter:on -->
									<replaceLineBased>false</replaceLineBased>
								</configuration>
							</execution>
							<execution>
								<!-- Changes with each generator version -->
								<id>remove-generated-annotation</id>
								<phase>process-sources</phase>
								<goals>
									<goal>file-contents</goal>
								</goals>
								<configuration>
									<baseDir>${generatedDirRelative}/software/xdev/${componentName}/</baseDir>
									<recursive>true</recursive>
									<fileMask>.java</fileMask>
									<findRegex>^@jakarta\.annotation\.Generated.*(\r?\n)</findRegex>
									<replaceAll>false</replaceAll>
									<replaceLineBased>false</replaceLineBased>
								</configuration>
							</execution>
							<execution>
								<!-- Requiring Java serialization indicates a serious misuse of the API -->
								<id>remove-serialVersionUID</id>
								<phase>process-sources</phase>
								<goals>
									<goal>file-contents</goal>
								</goals>
								<configuration>
									<baseDir>${generatedDirRelative}/software/xdev/${componentName}/</baseDir>
									<recursive>true</recursive>
									<fileMask>.java</fileMask>
									<findRegex>^.*serialVersionUID.*(\r?\n)(\s*\r?\n)?</findRegex>
									<replaceAll>false</replaceAll>
									<replaceLineBased>false</replaceLineBased>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>pmd</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-pmd-plugin</artifactId>
						<version>3.28.0</version>
						<configuration>
							<rulesets>
								<ruleset>../../.config/pmd/java/ruleset.xml</ruleset>
							</rulesets>
							<excludeRoots>
								<excludeRoot>${generatedDir}</excludeRoot>
							</excludeRoots>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
